#!/usr/bin/env ruby

# require "./src/api_client"
require_relative "src/runner"

# ApiClient.get_epics.select(&:started).reject(&:completed).sort_by(&:name).each do |e|
#   puts "#{e.id}: #{e.name}"
# end

# ApiClient.get_stories(72807).reject(&:completed).each do |s|
#   puts "#{s.id}: #{s.name}"
# end

runner = Runner.new
runner.load_initial_data
runner.loop
